### ISSUE TITLE
Watch Python Django Tutorial: Part 1

### ISSUE THREAD

**Issue by Hellrungj** [Hellrungj/Budget_Tracker#1]
## About
The project team needs to introduce to the Django framework. I have provided this video to tutorial watch below:  
[Python Django Tutorial: Full-Featured Web App Part 1 - Getting Started](https://www.youtube.com/watch?v=UmljXZIypDc&t=1s)

## Acceptance Criteria
- [x] Watch the video
- [x] Give some feedback or questions about the video in the comment section of the ticket

**Comment by mahkiwalker06** [comment]
So the Python I have on my computer is Python 3.9 is that okay? And will there be anything different with the processes that I need to worry about? Will it affect anything we are working on? I know you mentioned version 3.8

**Comment by mahkiwalker06** [comment]
sorry didnt mean to close that

**Comment by Hellrungj** [comment]
> So the Python I have on my computer is Python 3.9 is that okay? And will there be anything different from the processes that I need to worry about? Will it affect anything we are working on? I know you mentioned version 3.8

3.9 should be fine.

**Comment by Hellrungj** [comment]
Looks great.
