### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by Hellrungj** [Hellrungj/Budget_Tracker#3]
## About
The project team needs to introduce to the Django framework. I have provided this video to tutorial watch below:  
[REST API](https://www.youtube.com/watch?v=SLwpqD8n3d0)

## Acceptance Criteria
- [x] Watch the video
- [x] Give some feedback or questions about the video in the comment section of the ticket

**Comment by mahkiwalker06** [comment]
1. Get, Post,Put, Delete are all requests got it
2. Where are we putting these requests in our code editor or in our browser?
3. Will we be using http or https for this project?
I hope I'm not asking any dumb questions

**Comment by Hellrungj** [comment]
Great work!
